echo "------------Building for serial 0------------"
sed -i '/^CONFIG_ESP_CONSOLE_UART_NUM/s/^/#/' sdkconfig
sed -i '/^CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG/s/^/#/' sdkconfig
cat <<EOL >> sdkconfig
CONFIG_ESP_CONSOLE_UART_DEFAULT=y
CONFIG_ESP_CONSOLE_UART_NUM=0
CONFIG_ESP_CONSOLE_UART_BAUDRATE=115200
CONFIG_CONSOLE_UART_DEFAULT=y
CONFIG_CONSOLE_UART=y
CONFIG_CONSOLE_UART_NUM=0
CONFIG_CONSOLE_UART_BAUDRATE=115200
EOL


