

#include "driver/gpio.h"

/* Defines are not included by SWIG. We can provide a workaround by
 * creating an 'enum' that includes the GPIO_SEL_XX macros.
 */


typedef enum {
   GPIOSEL_0=GPIO_SEL_0,
   GPIOSEL_1=GPIO_SEL_1,
   GPIOSEL_2=GPIO_SEL_2,
   GPIOSEL_3=GPIO_SEL_3,
   GPIOSEL_4=GPIO_SEL_4,
   GPIOSEL_5=GPIO_SEL_5,
   GPIOSEL_6=GPIO_SEL_6,
   GPIOSEL_7=GPIO_SEL_7,
   GPIOSEL_8=GPIO_SEL_8,
   GPIOSEL_9=GPIO_SEL_9,
   GPIOSEL_10=GPIO_SEL_10,
   GPIOSEL_11=GPIO_SEL_11,
   GPIOSEL_12=GPIO_SEL_12,
   GPIOSEL_13=GPIO_SEL_13,
   GPIOSEL_14=GPIO_SEL_14,
   GPIOSEL_15=GPIO_SEL_15,
   GPIOSEL_16=GPIO_SEL_16,
   GPIOSEL_17=GPIO_SEL_17,
   GPIOSEL_18=GPIO_SEL_18,
   GPIOSEL_19=GPIO_SEL_19,
   GPIOSEL_20=GPIO_SEL_20,
   GPIOSEL_21=GPIO_SEL_21,
   GPIOSEL_22=GPIO_SEL_22,
   GPIOSEL_23=GPIO_SEL_23,
   GPIOSEL_25=GPIO_SEL_25,
} gpio_sel_t;

